=pod

=head1 NAME

fix-koha-conf

=head1 SYNOPSIS

    ./fix-koha-conf.sh mykoha

=head1 WARNING! 

This is very much an ongoing WORK IN PROGRESS!

=head1 BACKGROUND

See the following Koha bug reports for why this script is necessary:

=over 4

=item * L<http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=12584>

=item * L<http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=12577>

=back

=head1 AUTHOR

Magnus Enger, magnus@enger.prv.no

=head1 LICENSE

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=cut
